version: '3.8'

services:
  mssql:
    container_name: mssql-hayvansaglik
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Developer
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

  # Veritabanı kullanımını izlemek için Adminer ekleyebilirsiniz
  adminer:
    container_name: hayvansaglik-adminer
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mssql

networks:
  hayvansaglik-network:
    driver: bridge

volumes:
  mssql-data: